version: '3.8'
services:
  dokuwiki:
    image: 'bitnami/dokuwiki:latest'
    container_name: dokuwiki
    restart: unless-stopped
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      DOKUWIKI_USERNAME: admin
      DOKUWIKI_PASSWORD: admin
      TZ: Asia/Tokyo
    volumes:
      - ./dokuwiki:/dokuwiki
volumes:
  dokuwiki:
    driver: local
