version: '3.8'
services:
  dokuwiki:
    image: 'docker pull bitnami/dokuwiki:20200729.0.0-debian-10-r603'
    container_name: dokuwiki
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8443:443'
    environment:
      DOKUWIKI_USERNAME: admin
      DOKUWIKI_PASSWORD: admin
      TZ: Asia/Tokyo
    volumes:
      - dokuwiki:/bitnami/dokuwiki
volumes:
  dokuwiki:
    driver: local
